// LOCALHOST
### Get all contacts
GET http://localhost:3000/contacts

### Get contact by id
GET http://localhost:3000/contacts/6a05f3fe94ac61988b136b1b

### Create contact 
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "Case",
    "email": "testing@gmail.com",
    "favColor": "orange",
    "birthday": "2000-01-01"
}

### Update contact
PUT http://localhost:3000/contacts/6a0cfe609d9166b061098c38 HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "Case",
    "email": "testingcase@gmail.com",
    "favColor": "orange",
    "birthday": "2000-01-01"
}

### Delete contact
DELETE http://localhost:3000/contacts/6a0cfe609d9166b061098c38